#  spring.application.name=JournalApp
#    spring.data.mongodb.uri=mongodb+srv://sjain5144:sjain5144@cluster0.hifgg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#    spring.data.mongodb.database=journaldb
#    #spring.data.mongodb.username=sameer
#    #spring.data.mongodb.password=sameer
#    spring.data.mongodb.auto-index-creation=true

spring:
  data:
    mongodb:
      database: journaldb
      uri: mongodb+srv://sjain5144:sjain5144@cluster0.hifgg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
logging:
  level:
    com:
      sameer:
        journalApp: DEBUG


#priority given to application.properties not yaml
#there is also a way to give these using CLA
#CLA -> properties -> yaml